// <auto-generated />
//
// To parse this JSON data, add NuGet 'System.Text.Json' then do:
//
//    using QuickType.Map;
//
//    var ldtkData = LdtkData.FromJson(jsonString);
#nullable enable
#pragma warning disable CS8618
#pragma warning disable CS8601
#pragma warning disable CS8603

namespace QuickType.Map
{
    using System;
    using System.Collections.Generic;

    using System.Text.Json;
    using System.Text.Json.Serialization;
    using System.Globalization;

    public partial class LdtkData
    {
        [JsonPropertyName("__header__")]
        public Header Header { get; set; }

        [JsonPropertyName("iid")]
        public Guid Iid { get; set; }

        [JsonPropertyName("jsonVersion")]
        public string JsonVersion { get; set; }

        [JsonPropertyName("appBuildId")]
        public long AppBuildId { get; set; }

        [JsonPropertyName("nextUid")]
        public long NextUid { get; set; }

        [JsonPropertyName("identifierStyle")]
        public string IdentifierStyle { get; set; }

        [JsonPropertyName("toc")]
        public object[] Toc { get; set; }

        [JsonPropertyName("worldLayout")]
        public string WorldLayout { get; set; }

        [JsonPropertyName("worldGridWidth")]
        public long WorldGridWidth { get; set; }

        [JsonPropertyName("worldGridHeight")]
        public long WorldGridHeight { get; set; }

        [JsonPropertyName("defaultLevelWidth")]
        public long DefaultLevelWidth { get; set; }

        [JsonPropertyName("defaultLevelHeight")]
        public long DefaultLevelHeight { get; set; }

        [JsonPropertyName("defaultPivotX")]
        public long DefaultPivotX { get; set; }

        [JsonPropertyName("defaultPivotY")]
        public long DefaultPivotY { get; set; }

        [JsonPropertyName("defaultGridSize")]
        public long DefaultGridSize { get; set; }

        [JsonPropertyName("defaultEntityWidth")]
        public object DefaultEntityWidth { get; set; }

        [JsonPropertyName("defaultEntityHeight")]
        public object DefaultEntityHeight { get; set; }

        [JsonPropertyName("bgColor")]
        public string BgColor { get; set; }

        [JsonPropertyName("defaultLevelBgColor")]
        public string DefaultLevelBgColor { get; set; }

        [JsonPropertyName("minifyJson")]
        public bool MinifyJson { get; set; }

        [JsonPropertyName("externalLevels")]
        public bool ExternalLevels { get; set; }

        [JsonPropertyName("exportTiled")]
        public bool ExportTiled { get; set; }

        [JsonPropertyName("simplifiedExport")]
        public bool SimplifiedExport { get; set; }

        [JsonPropertyName("imageExportMode")]
        public ImageExportMode ImageExportMode { get; set; }

        [JsonPropertyName("exportLevelBg")]
        public bool ExportLevelBg { get; set; }

        [JsonPropertyName("pngFilePattern")]
        public object PngFilePattern { get; set; }

        [JsonPropertyName("backupOnSave")]
        public bool BackupOnSave { get; set; }

        [JsonPropertyName("backupLimit")]
        public long BackupLimit { get; set; }

        [JsonPropertyName("backupRelPath")]
        public object BackupRelPath { get; set; }

        [JsonPropertyName("levelNamePattern")]
        public string LevelNamePattern { get; set; }

        [JsonPropertyName("tutorialDesc")]
        public object TutorialDesc { get; set; }

        [JsonPropertyName("customCommands")]
        public object[] CustomCommands { get; set; }

        [JsonPropertyName("flags")]
        public object[] Flags { get; set; }

        [JsonPropertyName("defs")]
        public Defs Defs { get; set; }

        [JsonPropertyName("levels")]
        public Level[] Levels { get; set; }

        [JsonPropertyName("worlds")]
        public object[] Worlds { get; set; }

        [JsonPropertyName("dummyWorldIid")]
        public Guid DummyWorldIid { get; set; }
    }

    public partial class Defs
    {
        [JsonPropertyName("layers")]
        public Layer[] Layers { get; set; }

        [JsonPropertyName("entities")]
        public object[] Entities { get; set; }

        [JsonPropertyName("tilesets")]
        public Tileset[] Tilesets { get; set; }

        [JsonPropertyName("enums")]
        public object[] Enums { get; set; }

        [JsonPropertyName("externalEnums")]
        public object[] ExternalEnums { get; set; }

        [JsonPropertyName("levelFields")]
        public object[] LevelFields { get; set; }
    }

    public partial class Layer
    {
        [JsonPropertyName("__type")]
        public string Type { get; set; }

        [JsonPropertyName("identifier")]
        public string Identifier { get; set; }

        [JsonPropertyName("type")]
        public string LayerType { get; set; }

        [JsonPropertyName("uid")]
        public long Uid { get; set; }

        [JsonPropertyName("doc")]
        public object Doc { get; set; }

        [JsonPropertyName("uiColor")]
        public object UiColor { get; set; }

        [JsonPropertyName("gridSize")]
        public long GridSize { get; set; }

        [JsonPropertyName("guideGridWid")]
        public long GuideGridWid { get; set; }

        [JsonPropertyName("guideGridHei")]
        public long GuideGridHei { get; set; }

        [JsonPropertyName("displayOpacity")]
        public long DisplayOpacity { get; set; }

        [JsonPropertyName("inactiveOpacity")]
        public long InactiveOpacity { get; set; }

        [JsonPropertyName("hideInList")]
        public bool HideInList { get; set; }

        [JsonPropertyName("hideFieldsWhenInactive")]
        public bool HideFieldsWhenInactive { get; set; }

        [JsonPropertyName("canSelectWhenInactive")]
        public bool CanSelectWhenInactive { get; set; }

        [JsonPropertyName("renderInWorldView")]
        public bool RenderInWorldView { get; set; }

        [JsonPropertyName("pxOffsetX")]
        public long PxOffsetX { get; set; }

        [JsonPropertyName("pxOffsetY")]
        public long PxOffsetY { get; set; }

        [JsonPropertyName("parallaxFactorX")]
        public long ParallaxFactorX { get; set; }

        [JsonPropertyName("parallaxFactorY")]
        public long ParallaxFactorY { get; set; }

        [JsonPropertyName("parallaxScaling")]
        public bool ParallaxScaling { get; set; }

        [JsonPropertyName("requiredTags")]
        public object[] RequiredTags { get; set; }

        [JsonPropertyName("excludedTags")]
        public object[] ExcludedTags { get; set; }

        [JsonPropertyName("intGridValues")]
        public IntGridValue[] IntGridValues { get; set; }

        [JsonPropertyName("intGridValuesGroups")]
        public object[] IntGridValuesGroups { get; set; }

        [JsonPropertyName("autoRuleGroups")]
        public AutoRuleGroup[] AutoRuleGroups { get; set; }

        [JsonPropertyName("autoSourceLayerDefUid")]
        public object AutoSourceLayerDefUid { get; set; }

        [JsonPropertyName("tilesetDefUid")]
        public long TilesetDefUid { get; set; }

        [JsonPropertyName("tilePivotX")]
        public long TilePivotX { get; set; }

        [JsonPropertyName("tilePivotY")]
        public long TilePivotY { get; set; }
    }

    public partial class AutoRuleGroup
    {
        [JsonPropertyName("uid")]
        public long Uid { get; set; }

        [JsonPropertyName("name")]
        public string Name { get; set; }

        [JsonPropertyName("color")]
        public object Color { get; set; }

        [JsonPropertyName("icon")]
        public object Icon { get; set; }

        [JsonPropertyName("active")]
        public bool Active { get; set; }

        [JsonPropertyName("isOptional")]
        public bool IsOptional { get; set; }

        [JsonPropertyName("rules")]
        public Rule[] Rules { get; set; }

        [JsonPropertyName("usesWizard")]
        public bool UsesWizard { get; set; }
    }

    public partial class Rule
    {
        [JsonPropertyName("uid")]
        public long Uid { get; set; }

        [JsonPropertyName("active")]
        public bool Active { get; set; }

        [JsonPropertyName("size")]
        public long Size { get; set; }

        [JsonPropertyName("tileIds")]
        public long[] TileIds { get; set; }

        [JsonPropertyName("alpha")]
        public long Alpha { get; set; }

        [JsonPropertyName("chance")]
        public long Chance { get; set; }

        [JsonPropertyName("breakOnMatch")]
        public bool BreakOnMatch { get; set; }

        [JsonPropertyName("pattern")]
        public long[] Pattern { get; set; }

        [JsonPropertyName("flipX")]
        public bool FlipX { get; set; }

        [JsonPropertyName("flipY")]
        public bool FlipY { get; set; }

        [JsonPropertyName("xModulo")]
        public long XModulo { get; set; }

        [JsonPropertyName("yModulo")]
        public long YModulo { get; set; }

        [JsonPropertyName("xOffset")]
        public long XOffset { get; set; }

        [JsonPropertyName("yOffset")]
        public long YOffset { get; set; }

        [JsonPropertyName("tileXOffset")]
        public long TileXOffset { get; set; }

        [JsonPropertyName("tileYOffset")]
        public long TileYOffset { get; set; }

        [JsonPropertyName("tileRandomXMin")]
        public long TileRandomXMin { get; set; }

        [JsonPropertyName("tileRandomXMax")]
        public long TileRandomXMax { get; set; }

        [JsonPropertyName("tileRandomYMin")]
        public long TileRandomYMin { get; set; }

        [JsonPropertyName("tileRandomYMax")]
        public long TileRandomYMax { get; set; }

        [JsonPropertyName("checker")]
        public ImageExportMode Checker { get; set; }

        [JsonPropertyName("tileMode")]
        public TileMode TileMode { get; set; }

        [JsonPropertyName("pivotX")]
        public long PivotX { get; set; }

        [JsonPropertyName("pivotY")]
        public long PivotY { get; set; }

        [JsonPropertyName("outOfBoundsValue")]
        public long OutOfBoundsValue { get; set; }

        [JsonPropertyName("perlinActive")]
        public bool PerlinActive { get; set; }

        [JsonPropertyName("perlinSeed")]
        public long PerlinSeed { get; set; }

        [JsonPropertyName("perlinScale")]
        public double PerlinScale { get; set; }

        [JsonPropertyName("perlinOctaves")]
        public long PerlinOctaves { get; set; }
    }

    public partial class IntGridValue
    {
        [JsonPropertyName("value")]
        public long Value { get; set; }

        [JsonPropertyName("identifier")]
        public object Identifier { get; set; }

        [JsonPropertyName("color")]
        public string Color { get; set; }

        [JsonPropertyName("tile")]
        public object Tile { get; set; }

        [JsonPropertyName("groupUid")]
        public long GroupUid { get; set; }
    }

    public partial class Tileset
    {
        [JsonPropertyName("__cWid")]
        public long CWid { get; set; }

        [JsonPropertyName("__cHei")]
        public long CHei { get; set; }

        [JsonPropertyName("identifier")]
        public string Identifier { get; set; }

        [JsonPropertyName("uid")]
        public long Uid { get; set; }

        [JsonPropertyName("relPath")]
        public string RelPath { get; set; }

        [JsonPropertyName("embedAtlas")]
        public object EmbedAtlas { get; set; }

        [JsonPropertyName("pxWid")]
        public long PxWid { get; set; }

        [JsonPropertyName("pxHei")]
        public long PxHei { get; set; }

        [JsonPropertyName("tileGridSize")]
        public long TileGridSize { get; set; }

        [JsonPropertyName("spacing")]
        public long Spacing { get; set; }

        [JsonPropertyName("padding")]
        public long Padding { get; set; }

        [JsonPropertyName("tags")]
        public object[] Tags { get; set; }

        [JsonPropertyName("tagsSourceEnumUid")]
        public object TagsSourceEnumUid { get; set; }

        [JsonPropertyName("enumTags")]
        public object[] EnumTags { get; set; }

        [JsonPropertyName("customData")]
        public object[] CustomData { get; set; }

        [JsonPropertyName("savedSelections")]
        public object[] SavedSelections { get; set; }

        [JsonPropertyName("cachedPixelData")]
        public CachedPixelData CachedPixelData { get; set; }
    }

    public partial class CachedPixelData
    {
        [JsonPropertyName("opaqueTiles")]
        public string OpaqueTiles { get; set; }

        [JsonPropertyName("averageColors")]
        public string AverageColors { get; set; }
    }

    public partial class Header
    {
        [JsonPropertyName("fileType")]
        public string FileType { get; set; }

        [JsonPropertyName("app")]
        public string App { get; set; }

        [JsonPropertyName("doc")]
        public Uri Doc { get; set; }

        [JsonPropertyName("schema")]
        public Uri Schema { get; set; }

        [JsonPropertyName("appAuthor")]
        public string AppAuthor { get; set; }

        [JsonPropertyName("appVersion")]
        public string AppVersion { get; set; }

        [JsonPropertyName("url")]
        public Uri Url { get; set; }
    }

    public partial class Level
    {
        [JsonPropertyName("identifier")]
        public string Identifier { get; set; }

        [JsonPropertyName("iid")]
        public Guid Iid { get; set; }

        [JsonPropertyName("uid")]
        public long Uid { get; set; }

        [JsonPropertyName("worldX")]
        public long WorldX { get; set; }

        [JsonPropertyName("worldY")]
        public long WorldY { get; set; }

        [JsonPropertyName("worldDepth")]
        public long WorldDepth { get; set; }

        [JsonPropertyName("pxWid")]
        public long PxWid { get; set; }

        [JsonPropertyName("pxHei")]
        public long PxHei { get; set; }

        [JsonPropertyName("__bgColor")]
        public string BgColor { get; set; }

        [JsonPropertyName("bgColor")]
        public object LevelBgColor { get; set; }

        [JsonPropertyName("useAutoIdentifier")]
        public bool UseAutoIdentifier { get; set; }

        [JsonPropertyName("bgRelPath")]
        public object BgRelPath { get; set; }

        [JsonPropertyName("bgPos")]
        public object LevelBgPos { get; set; }

        [JsonPropertyName("bgPivotX")]
        public double BgPivotX { get; set; }

        [JsonPropertyName("bgPivotY")]
        public double BgPivotY { get; set; }

        [JsonPropertyName("__smartColor")]
        public string SmartColor { get; set; }

        [JsonPropertyName("__bgPos")]
        public object BgPos { get; set; }

        [JsonPropertyName("externalRelPath")]
        public object ExternalRelPath { get; set; }

        [JsonPropertyName("fieldInstances")]
        public object[] FieldInstances { get; set; }

        [JsonPropertyName("layerInstances")]
        public LayerInstance[] LayerInstances { get; set; }

        [JsonPropertyName("__neighbours")]
        public object[] Neighbours { get; set; }
    }

    public partial class LayerInstance
    {
        [JsonPropertyName("__identifier")]
        public string Identifier { get; set; }

        [JsonPropertyName("__type")]
        public string Type { get; set; }

        [JsonPropertyName("__cWid")]
        public long CWid { get; set; }

        [JsonPropertyName("__cHei")]
        public long CHei { get; set; }

        [JsonPropertyName("__gridSize")]
        public long GridSize { get; set; }

        [JsonPropertyName("__opacity")]
        public long Opacity { get; set; }

        [JsonPropertyName("__pxTotalOffsetX")]
        public long PxTotalOffsetX { get; set; }

        [JsonPropertyName("__pxTotalOffsetY")]
        public long PxTotalOffsetY { get; set; }

        [JsonPropertyName("__tilesetDefUid")]
        public long TilesetDefUid { get; set; }

        [JsonPropertyName("__tilesetRelPath")]
        public string TilesetRelPath { get; set; }

        [JsonPropertyName("iid")]
        public Guid Iid { get; set; }

        [JsonPropertyName("levelId")]
        public long LevelId { get; set; }

        [JsonPropertyName("layerDefUid")]
        public long LayerDefUid { get; set; }

        [JsonPropertyName("pxOffsetX")]
        public long PxOffsetX { get; set; }

        [JsonPropertyName("pxOffsetY")]
        public long PxOffsetY { get; set; }

        [JsonPropertyName("visible")]
        public bool Visible { get; set; }

        [JsonPropertyName("optionalRules")]
        public object[] OptionalRules { get; set; }

        [JsonPropertyName("intGridCsv")]
        public long[] IntGridCsv { get; set; }

        [JsonPropertyName("autoLayerTiles")]
        public Tile[] AutoLayerTiles { get; set; }

        [JsonPropertyName("seed")]
        public long Seed { get; set; }

        [JsonPropertyName("overrideTilesetUid")]
        public object OverrideTilesetUid { get; set; }

        [JsonPropertyName("gridTiles")]
        public Tile[] GridTiles { get; set; }

        [JsonPropertyName("entityInstances")]
        public object[] EntityInstances { get; set; }
    }

    public partial class Tile
    {
        [JsonPropertyName("px")]
        public long[] Px { get; set; }

        [JsonPropertyName("src")]
        public long[] Src { get; set; }

        [JsonPropertyName("f")]
        public long F { get; set; }

        [JsonPropertyName("t")]
        public long T { get; set; }

        [JsonPropertyName("d")]
        public long[] D { get; set; }

        [JsonPropertyName("a")]
        public long A { get; set; }
    }

    public enum ImageExportMode { None };

    public enum TileMode { Single };

    public partial class LdtkData
    {
        public static LdtkData FromJson(string json) => JsonSerializer.Deserialize<LdtkData>(json, QuickType.Map.Converter.Settings);
    }

    public static class Serialize
    {
        public static string ToJson(this LdtkData self) => JsonSerializer.Serialize(self, QuickType.Map.Converter.Settings);
    }

    internal static class Converter
    {
        public static readonly JsonSerializerOptions Settings = new(JsonSerializerDefaults.General)
        {
            Converters =
            {
                ImageExportModeConverter.Singleton,
                TileModeConverter.Singleton,
                new DateOnlyConverter(),
                new TimeOnlyConverter(),
                IsoDateTimeOffsetConverter.Singleton
            },
        };
    }

    internal class ImageExportModeConverter : JsonConverter<ImageExportMode>
    {
        public override bool CanConvert(Type t) => t == typeof(ImageExportMode);

        public override ImageExportMode Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        {
            var value = reader.GetString();
            if (value == "None")
            {
                return ImageExportMode.None;
            }
            throw new Exception("Cannot unmarshal type ImageExportMode");
        }

        public override void Write(Utf8JsonWriter writer, ImageExportMode value, JsonSerializerOptions options)
        {
            if (value == ImageExportMode.None)
            {
                JsonSerializer.Serialize(writer, "None", options);
                return;
            }
            throw new Exception("Cannot marshal type ImageExportMode");
        }

        public static readonly ImageExportModeConverter Singleton = new ImageExportModeConverter();
    }

    internal class TileModeConverter : JsonConverter<TileMode>
    {
        public override bool CanConvert(Type t) => t == typeof(TileMode);

        public override TileMode Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        {
            var value = reader.GetString();
            if (value == "Single")
            {
                return TileMode.Single;
            }
            throw new Exception("Cannot unmarshal type TileMode");
        }

        public override void Write(Utf8JsonWriter writer, TileMode value, JsonSerializerOptions options)
        {
            if (value == TileMode.Single)
            {
                JsonSerializer.Serialize(writer, "Single", options);
                return;
            }
            throw new Exception("Cannot marshal type TileMode");
        }

        public static readonly TileModeConverter Singleton = new TileModeConverter();
    }

    public class DateOnlyConverter : JsonConverter<DateOnly>
    {
        private readonly string serializationFormat;
        public DateOnlyConverter() : this(null) { }

        public DateOnlyConverter(string? serializationFormat)
        {
            this.serializationFormat = serializationFormat ?? "yyyy-MM-dd";
        }

        public override DateOnly Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        {
            var value = reader.GetString();
            return DateOnly.Parse(value!);
        }

        public override void Write(Utf8JsonWriter writer, DateOnly value, JsonSerializerOptions options)
            => writer.WriteStringValue(value.ToString(serializationFormat));
    }

    public class TimeOnlyConverter : JsonConverter<TimeOnly>
    {
        private readonly string serializationFormat;

        public TimeOnlyConverter() : this(null) { }

        public TimeOnlyConverter(string? serializationFormat)
        {
            this.serializationFormat = serializationFormat ?? "HH:mm:ss.fff";
        }

        public override TimeOnly Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        {
            var value = reader.GetString();
            return TimeOnly.Parse(value!);
        }

        public override void Write(Utf8JsonWriter writer, TimeOnly value, JsonSerializerOptions options)
            => writer.WriteStringValue(value.ToString(serializationFormat));
    }

    internal class IsoDateTimeOffsetConverter : JsonConverter<DateTimeOffset>
    {
        public override bool CanConvert(Type t) => t == typeof(DateTimeOffset);

        private const string DefaultDateTimeFormat = "yyyy'-'MM'-'dd'T'HH':'mm':'ss.FFFFFFFK";

        private DateTimeStyles _dateTimeStyles = DateTimeStyles.RoundtripKind;
        private string? _dateTimeFormat;
        private CultureInfo? _culture;

        public DateTimeStyles DateTimeStyles
        {
            get => _dateTimeStyles;
            set => _dateTimeStyles = value;
        }

        public string? DateTimeFormat
        {
            get => _dateTimeFormat ?? string.Empty;
            set => _dateTimeFormat = (string.IsNullOrEmpty(value)) ? null : value;
        }

        public CultureInfo Culture
        {
            get => _culture ?? CultureInfo.CurrentCulture;
            set => _culture = value;
        }

        public override void Write(Utf8JsonWriter writer, DateTimeOffset value, JsonSerializerOptions options)
        {
            string text;


            if ((_dateTimeStyles & DateTimeStyles.AdjustToUniversal) == DateTimeStyles.AdjustToUniversal
                || (_dateTimeStyles & DateTimeStyles.AssumeUniversal) == DateTimeStyles.AssumeUniversal)
            {
                value = value.ToUniversalTime();
            }

            text = value.ToString(_dateTimeFormat ?? DefaultDateTimeFormat, Culture);

            writer.WriteStringValue(text);
        }

        public override DateTimeOffset Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        {
            string? dateText = reader.GetString();

            if (string.IsNullOrEmpty(dateText) == false)
            {
                if (!string.IsNullOrEmpty(_dateTimeFormat))
                {
                    return DateTimeOffset.ParseExact(dateText, _dateTimeFormat, Culture, _dateTimeStyles);
                }
                else
                {
                    return DateTimeOffset.Parse(dateText, Culture, _dateTimeStyles);
                }
            }
            else
            {
                return default(DateTimeOffset);
            }
        }


        public static readonly IsoDateTimeOffsetConverter Singleton = new IsoDateTimeOffsetConverter();
    }
}
#pragma warning restore CS8618
#pragma warning restore CS8601
#pragma warning restore CS8603
